# create snapshot for each vm
- name: Check Snapshot exists for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
  stat: path="{{work_dir}}/{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}-{{vm_type.size}}GB.qcow2"
  register: snapshot
- name: Create snapshot for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}} if not exists
  block:
  - name: Create snapshot for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
    shell: qemu-img create -f qcow2 -b {{work_dir}}/{{image_url_file}}-{{vm_type.size}}GB.qcow2 {{work_dir}}/{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}-{{vm_type.size}}GB.qcow2
  when: not snapshot.stat.exists
