- name: Set kubeadm-config.yaml
  become: yes
  template:
    src: files/kubeadm-config.yaml
    dest: /root/kubeadm-config.yaml
- name: Init kubeadm
  become: yes
  shell: kubeadm init --config /root/kubeadm-config.yaml --upload-certs
- name: Restart containerd
  become: yes
  service:
    name: containerd.service
    state: restarted
- name: Apply Flannel
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.16.3/Documentation/kube-flannel.yml
  when: cni == "flannel"
- name: Set calico.yaml
  # based on https://docs.projectcalico.org/manifests/tigera-operator.yaml
  become: yes
  template:
    src: files/calico.yaml
    dest: /tmp/calico.yaml
  when: cni == "calico"
- name: Apply Calico
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: kubectl apply -f /tmp/calico.yaml
  when: cni == "calico"
