- name: Set kubeadm-config.yaml
  become: yes
  template:
    src: files/kubeadm-config.yaml
    dest: /root/kubeadm-config.yaml
- name: Init kubeadm
  become: yes
  shell: kubeadm init --config /root/kubeadm-config.yaml --upload-certs
- name: Restart containerd
  become: yes
  service:
    name: containerd.service
    state: restarted
- name: Apply Flannel
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.16.3/Documentation/kube-flannel.yml
  when: cni == "flannel"
- name: Apply Calico Operator
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  # `apply` returns error
  shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml
  when: cni == "calico"
- name: Set calico-crd.yaml
  become: yes
  template:
    src: files/calico-crd.yaml
    dest: /tmp/calico-crd.yaml
  when: cni == "calico"
- name: Apply Calico CRD
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: kubectl apply -f /tmp/calico-crd.yaml
  when: cni == "calico"
