# Start each VM
- name: Get status for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
  virt:
    uri: "{{libvirt_uri}}"
    name: "{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}"
    command: status
  register: vm_status
- name: Start VM for {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}, if its status is `shutdown`
  virt:
    uri: "{{libvirt_uri}}"
    name: "{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}"
    command: start
  when: vm_status.status == "shutdown"