- name: Taint master nodes
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: "kubectl taint nodes --all node-role.kubernetes.io/master-"
  when: "'master' in group_names and tainted"
  ignore_errors: yes
