- name: Print join command
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: kubeadm token create --print-join-command
  register: join_command
- name: Register join command
  set_fact:
    join_command: "{{join_command.stdout}}"
