- name: Register certificate_key
  set_fact:
    certificate_key: "{{hostvars[groups['master'][0]].certificate_key}}"
- name: Register join_command for worker
  set_fact:
    join_command: "{{hostvars[groups['master'][0]].join_command}} --cri-socket=unix:///run/containerd/containerd.sock"
- name: Edit join command for master
  set_fact:
    join_command: "{{join_command}} --control-plane --certificate-key={{certificate_key}}"
  when: "'master' in group_names"
- name: Join node
  become: yes
  shell: "{{join_command}}"
- name: Restart containerd
  become: yes
  service:
    name: containerd.service
    state: restarted
