version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3
    ports:
      - "2379:2379"
    volumes:
      - "etcd_data:/default.etcd"
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:2379,http://etcd:2379
    restart: always
  coredns:
    image: coredns/coredns:1.1.4
    command:
      - -conf
      - /Corefile
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - "./Corefile:/Corefile"
    restart: always
volumes:
    etcd_data:
