apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test-1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/test1
    server: frontend

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test-2
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/test2
    server: frontend

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test-5
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/test5
    server: frontend

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-claim-1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: slow

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-claim-2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
  storageClassName: slow

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-claim-5
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: slow

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: nfs-quota
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: "1000Mi"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: g
data:
  g.o: 00
  g.f: freedom
  g.u: unicorn
