apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nginx-fd
  name: nfs-nginx-log
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/nginx-log
    server: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: nginx-fd
  name: nfs-nginx-log
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      type: webserver
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    type: nginx-fd
  name: fluentd-conf
data:
  fluentd.conf: |
    <source>
      @type tail
      format none
      path /var/log/nginx/access.log
      tag count.format1
    </source>

    <match *.**>
      @type forward

      <server>
        name localhost
        host 127.0.0.1
      </server>
    </match>
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: nginx-fd
  name: nginx-with-fluentd
spec:
  selector:
    type: webserver
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    type: nginx-fd
  name: nginx-with-fluentd
spec:
  volumes:
    - name: log-dir
      persistentVolumeClaim:
        claimName: nfs-nginx-log
    - name: log-conf
      configMap:
        name: fluentd-conf
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: log-dir
        mountPath: "/var/log/nginx/"
  - name: fdlogger
    image: k8s.gcr.io/fluentd-gcp:1.30
    env:
    - name: FLUENTD_ARGS
      value: -c /etc/fluentd-config/fluentd.conf
    volumeMounts:
      - name: log-dir
        mountPath: "/var/log"
      - name: log-conf
        mountPath: "/etc/fluentd-config"
  