# create or update cloud init for each vm
- name: Hash password for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
  shell: mkpasswd --method=SHA-512 --rounds=4096 {{vm_type.password}}
  register: hashed_password
- name: Create/Update cloud config file for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
  template: src=templates/cloud-config.j2 dest={{work_dir}}/{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}.cloud
- name: Create/Update network config file for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
  template: src=templates/network-config.j2 dest={{work_dir}}/{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}.network
- name: Create/Update cloud init disk image from file for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
  shell: cloud-localds --network-config={{work_dir}}/{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}.network {{work_dir}}/{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}.cloud.cdrom {{work_dir}}/{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}.cloud
