# Shutdown each VM
- name: Get status for VM {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}
  virt:
    uri: "{{libvirt_uri}}"
    name: "{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}"
    command: status
  register: vm_status
- name: Shutdown VM for {{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}, if its status is not `shutdown`
  virt:
    uri: "{{libvirt_uri}}"
    name: "{{stage}}-{{cluster_type}}-{{vm_type.type}}-{{vm.name}}"
    command: shutdown
  when: vm_status.status != "shutdown"